/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passagensrodoviarias;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabri
 */
public class TelaCidade extends javax.swing.JFrame {

    /**
     * Creates new form TelaCidade
     */
    
    private static final String URL = "jdbc:mysql://localhost:3306/passagens";
    private static final String USER = "root";
    private static final String PASSWORD = "";
    
    public TelaCidade() {
        initComponents();
        
        carregarDadosTabela();
        setTitle("INFORMAÇÕES DOS ÔNIBUS");
        setSize(1280, 860);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ((DefaultTableCellRenderer)tableCidades.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(SwingConstants.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for(int i=0; i<tableCidades.getColumnCount(); i++) {
            tableCidades.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }   
    
    private void carregarDadosTabela() {
        try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD)) {
            String sql = "SELECT nome_cidade, sigla_ibge, uf FROM cidades";
         
            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
                try (ResultSet rs = pstmt.executeQuery()) {
                    DefaultTableModel model = (DefaultTableModel) tableCidades.getModel();
                    model.setRowCount(0);
                    while (rs.next()) {
                        Object[] rowData = {rs.getString("nome_cidade"), rs.getString("sigla_ibge"), rs.getString("uf")};
                        model.addRow(rowData);
                    }
                    // Jogar dados da celula qtd poltronas para esquerda.
//                    tableCidades.getColumnModel().getColumn(3).setCellRenderer(new DefaultTableCellRenderer() {
//                        {
//                            setHorizontalAlignment(SwingConstants.LEFT);
//                        }
//                    });
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados da tabela: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void atualizarTabelaCidade() {
        DefaultTableModel model = (DefaultTableModel) tableCidades.getModel();
        model.setRowCount(0);

        try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD)) {
            String sql = "SELECT nome_cidade, sigla_ibge, uf FROM cidades";
            try (PreparedStatement pstmt = conn.prepareStatement(sql);
                 ResultSet rs = pstmt.executeQuery()) {
                
                while (rs.next()) {
                    model.addRow(new Object[]{rs.getString("nome_cidade"), rs.getString("sigla_ibge"),
                            rs.getString("uf")});
                }
            }
        } catch (SQLException ex) {
            System.out.println("Erro ao atualizar tabela de cidades: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCidades = new javax.swing.JTable();
        searchCidade = new javax.swing.JButton();
        adicionarCidade = new javax.swing.JButton();
        atualizarCidade = new javax.swing.JButton();
        excluirCidade = new javax.swing.JButton();
        buttonVoltar = new javax.swing.JButton();
        searchNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        searchSigla = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchUf = new javax.swing.JTextField();
        editarCidade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CROSSBUS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 64)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CIDADES");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        tableCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cidade", "Sigla", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableCidades.setColumnSelectionAllowed(true);
        tableCidades.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableCidades);
        tableCidades.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 780, 480));

        searchCidade.setText("Consultar");
        searchCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(searchCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 240, 110, 40));

        adicionarCidade.setText("Adicionar");
        adicionarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(adicionarCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 420, 110, 40));

        atualizarCidade.setText("Atualizar");
        atualizarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(atualizarCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 640, 110, 40));

        excluirCidade.setText("Excluir cidade");
        excluirCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(excluirCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 750, 110, 40));

        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 750, 110, 40));

        searchNome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchNomeActionPerformed(evt);
            }
        });
        jPanel1.add(searchNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 270, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cidade");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sigla");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        searchSigla.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSiglaActionPerformed(evt);
            }
        });
        jPanel1.add(searchSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 130, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UF");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, -1, -1));
        jPanel1.add(searchUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 240, 70, 40));

        editarCidade.setText("Editar cidade");
        editarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCidadeActionPerformed(evt);
            }
        });
        jPanel1.add(editarCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 530, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCidadeActionPerformed
        String cidade = searchNome.getText().trim();
        String sigla = searchSigla.getText().trim();
        String uf = searchUf.getText().trim();

        StringBuilder sqlBuilder = new StringBuilder();
        sqlBuilder.append("SELECT nome_cidade, sigla_ibge, uf FROM cidades WHERE 1=1");
        List<Object> params = new ArrayList<>();
        
        if (!cidade.isEmpty()) {
            sqlBuilder.append(" AND nome_cidade LIKE ?");
            params.add("%" + cidade + "%"); // Adiciona o caractere '%' para pesquisar por substrings
        }
        if (!sigla.isEmpty()) {
            sqlBuilder.append(" AND sigla_ibge LIKE ?");
            params.add("%" + sigla + "%");
        }
        if (!uf.isEmpty()) {
            sqlBuilder.append(" AND uf LIKE ?");
            params.add("%" + uf + "%");
        }
        
        try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD)) {
            try (PreparedStatement pstmt = conn.prepareStatement(sqlBuilder.toString())) {
                
                for (int i = 0; i < params.size(); i++) {
                    pstmt.setObject(i + 1, params.get(i));
                }
            
                try (ResultSet rs = pstmt.executeQuery()) {
                    DefaultTableModel model = (DefaultTableModel) tableCidades.getModel();
                    model.setRowCount(0);
                    while (rs.next()) {
                        Object[] rowData = {rs.getString("nome_cidade"), rs.getString("sigla_ibge"), rs.getString("uf")};
                        model.addRow(rowData);
                    }
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao executar consulta: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
   
    }//GEN-LAST:event_searchCidadeActionPerformed

    private void adicionarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCidadeActionPerformed

        CadastrarCidade cadastrarCidade = new CadastrarCidade();
        cadastrarCidade.setVisible(true);

    }//GEN-LAST:event_adicionarCidadeActionPerformed

    private void atualizarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCidadeActionPerformed
      atualizarTabelaCidade();
    }//GEN-LAST:event_atualizarCidadeActionPerformed

    private void excluirCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCidadeActionPerformed
        excluirDados();
    }//GEN-LAST:event_excluirCidadeActionPerformed

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void searchNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchNomeActionPerformed

    }//GEN-LAST:event_searchNomeActionPerformed

    private void searchSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSiglaActionPerformed

    }//GEN-LAST:event_searchSiglaActionPerformed

    private void editarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCidadeActionPerformed

    }//GEN-LAST:event_editarCidadeActionPerformed

    private int getLinhaSelecionada() {
        return tableCidades.getSelectedRow();
    }
    
    private void excluirDados() {
        int linhaSelecionada = getLinhaSelecionada();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Confirmar exclusão com o usuário
        int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir esta cidade?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta != JOptionPane.YES_OPTION) {
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tableCidades.getModel();
        String cidade = (String) model.getValueAt(linhaSelecionada, 0);

        try (Connection conn = DriverManager.getConnection(URL, USER, PASSWORD)) {
            String sql = "DELETE FROM cidades WHERE nome_cidade = ?";

            try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
                pstmt.setString(1, cidade);

                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Dados excluídos com sucesso.");
                    carregarDadosTabela();
                } else {
                    JOptionPane.showMessageDialog(this, "Nenhum dado foi excluído.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir dados: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCidade;
    private javax.swing.JButton atualizarCidade;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JButton editarCidade;
    private javax.swing.JButton excluirCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchCidade;
    private javax.swing.JTextField searchNome;
    private javax.swing.JTextField searchSigla;
    private javax.swing.JTextField searchUf;
    private javax.swing.JTable tableCidades;
    // End of variables declaration//GEN-END:variables
}
