/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passagensrodoviarias;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author miguelvarjao
 */
public class TelaPagamento extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/passagens";
    private static final String USER = "root";
    private static final String PASSWORD = "SetRootPasswordHere";
    
    public TelaPagamento() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        setSize(720, 560);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        ((AbstractDocument) campoCartao.getDocument()).setDocumentFilter(new NumberOnlyFilter(16));

    }
    class NumberOnlyFilter extends DocumentFilter {
    private int maxLength;

    public NumberOnlyFilter(int maxLength) {
        this.maxLength = maxLength;
    }

    @Override
    public void insertString(FilterBypass fb, int offset, String text,
            AttributeSet attr) throws BadLocationException {
        String newText = new StringBuilder(fb.getDocument().getText(0, fb.getDocument().getLength()))
            .insert(offset, text).toString();
        if (isNumber(text) && newText.replaceAll("\\D", "").length() <= maxLength) {
        StringBuilder formattedText = new StringBuilder();
        int count = 0;
        for (int i = 0; i < newText.length(); i++) {
            char c = newText.charAt(i);
            if (Character.isDigit(c)) {
                if (count > 0 && count % 4 == 0) {
                    formattedText.append("-");
                }
                formattedText.append(c);
                count++;
            }
        }
        super.insertString(fb, offset, formattedText.toString(), attr);
    }
    }

    
    @Override
    public void replace(FilterBypass fb, int offset, int length, String text,
            AttributeSet attrs) throws BadLocationException {
        if (isNumber(text) && (fb.getDocument().getLength() + text.length() - length <= maxLength)) {
            super.replace(fb, offset, length, text, attrs);
        }
    }
    
    
    private boolean isNumber(String text) {
        return text != null && text.matches("\\d+");
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoPagamento = new javax.swing.JLabel();
        pagamento = new javax.swing.JLabel();
        logoVisa = new javax.swing.JLabel();
        logoMaster = new javax.swing.JLabel();
        Cartao = new javax.swing.JLabel();
        campoCartao = new javax.swing.JTextField();
        proprietario = new javax.swing.JLabel();
        campoProprietario = new javax.swing.JTextField();
        mes = new javax.swing.JLabel();
        ano = new javax.swing.JLabel();
        campoMes = new javax.swing.JTextField();
        campoAno = new javax.swing.JTextField();
        cvc = new javax.swing.JLabel();
        campoCVC = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        tituloTela = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/credit-card.png"))); // NOI18N
        getContentPane().add(logoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        pagamento.setFont(new java.awt.Font("Jamrul", 0, 15)); // NOI18N
        pagamento.setForeground(new java.awt.Color(102, 102, 102));
        pagamento.setText("Pagamento");
        getContentPane().add(pagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 124, -1, 30));

        logoVisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/card.png"))); // NOI18N
        getContentPane().add(logoVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        logoMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mastercard.png"))); // NOI18N
        getContentPane().add(logoMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        Cartao.setFont(new java.awt.Font("Jamrul", 0, 15)); // NOI18N
        Cartao.setForeground(new java.awt.Color(102, 102, 102));
        Cartao.setText("Número do cartão");
        getContentPane().add(Cartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        campoCartao.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        campoCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCartaoActionPerformed(evt);
            }
        });
        getContentPane().add(campoCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 239, -1));

        proprietario.setFont(new java.awt.Font("Jamrul", 0, 15)); // NOI18N
        proprietario.setForeground(new java.awt.Color(102, 102, 102));
        proprietario.setText("Nome do proprietário do cartão");
        getContentPane().add(proprietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, -1, -1));

        campoProprietario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        campoProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoProprietarioActionPerformed(evt);
            }
        });
        getContentPane().add(campoProprietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 239, -1));

        mes.setFont(new java.awt.Font("Jamrul", 0, 15)); // NOI18N
        mes.setForeground(new java.awt.Color(102, 102, 102));
        mes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mes.setText("Mês");
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 270, 60, -1));

        ano.setFont(new java.awt.Font("Jamrul", 0, 15)); // NOI18N
        ano.setForeground(new java.awt.Color(102, 102, 102));
        ano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ano.setText("Ano");
        getContentPane().add(ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 60, -1));

        campoMes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(campoMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 60, -1));

        campoAno.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(campoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 60, -1));

        cvc.setFont(new java.awt.Font("Jamrul", 0, 15)); // NOI18N
        cvc.setForeground(new java.awt.Color(102, 102, 102));
        cvc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cvc.setText("CVC");
        getContentPane().add(cvc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 60, 20));

        campoCVC.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(campoCVC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 60, 30));

        btSalvar.setBackground(new java.awt.Color(102, 102, 255));
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSalvarMouseClicked(evt);
            }
        });
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 170, 40));

        tituloTela.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Adicionar novo cartão");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back.png"))); // NOI18N

        javax.swing.GroupLayout tituloTelaLayout = new javax.swing.GroupLayout(tituloTela);
        tituloTela.setLayout(tituloTelaLayout);
        tituloTelaLayout.setHorizontalGroup(
            tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloTelaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(481, Short.MAX_VALUE))
        );
        tituloTelaLayout.setVerticalGroup(
            tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tituloTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tituloTelaLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
        );

        getContentPane().add(tituloTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCartaoActionPerformed

    private void campoProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoProprietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoProprietarioActionPerformed

    private void btSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSalvarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalvarMouseClicked

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
      String numeroCartao = campoCartao.getText().replaceAll("[^0-9]", "");
    String nomeProprietario = campoProprietario.getText();
    String mesExpiracao = campoMes.getText();
    String anoExpiracao = campoAno.getText();
    String cvv = campoCVC.getText();
    int idUsuario = 1; // Defina o ID do usuário aqui
    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/passagens", "root", "SetRootPasswordHere")) {
        String sql = "INSERT INTO dadoscartao (numero_cartao, nome_proprietario, mes_expiracao, ano_expiracao, cvv, id_usuario) VALUES (?, ?, ?, ?, ?, ?)";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, numeroCartao);
            statement.setString(2, nomeProprietario);
            statement.setString(3, mesExpiracao);
            statement.setString(4, anoExpiracao);
            statement.setString(5, cvv);
            statement.setInt(6, idUsuario);

            int rowsInserted = statement.executeUpdate();
            if (rowsInserted > 0) {
                System.out.println("Dados do cartão salvos com sucesso!");
            } else {
                System.out.println("Falha ao salvar os dados do cartão.");
            }
        }
    } catch (SQLException e) {
        System.err.println("Erro ao conectar ao banco de dados: " + e.getMessage());
    }
    }//GEN-LAST:event_btSalvarActionPerformed
private void formatarNumeroCartao() {
    String texto = campoCartao.getText().replaceAll("[^0-9]", "");
    StringBuilder formato = new StringBuilder();
    
    for (int i = 0; i < texto.length(); i++) {
        if (i > 0 && i % 4 == 0) {
            formato.append("-");
        }
        formato.append(texto.charAt(i));
    }
    
    Cartao.setText(formato.toString());
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cartao;
    private javax.swing.JLabel ano;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoCVC;
    private javax.swing.JTextField campoCartao;
    private javax.swing.JTextField campoMes;
    private javax.swing.JTextField campoProprietario;
    private javax.swing.JLabel cvc;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel logoMaster;
    private javax.swing.JLabel logoPagamento;
    private javax.swing.JLabel logoVisa;
    private javax.swing.JLabel mes;
    private javax.swing.JLabel pagamento;
    private javax.swing.JLabel proprietario;
    private javax.swing.JPanel tituloTela;
    // End of variables declaration//GEN-END:variables
}
