/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passagensrodoviarias;

/**
 *
 * @author gabrielpaiva
 */
import javax.swing.JOptionPane;
public class telaHome extends javax.swing.JFrame {
    
    /**
     * Creates new form telaHome
     */
    public telaHome() {
        initComponents();
         setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeDoUsuario = new javax.swing.JLabel();
        tituloTela = new javax.swing.JLabel();
        painel = new javax.swing.JPanel();
        tituloEmpresa = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        painelInteracao = new javax.swing.JPanel();
        iconVeiculos = new javax.swing.JLabel();
        veiculos = new javax.swing.JLabel();
        iconViagens = new javax.swing.JLabel();
        viagens = new javax.swing.JLabel();
        iconPassagens = new javax.swing.JLabel();
        passagensVendidas = new javax.swing.JLabel();
        iconFaturamento = new javax.swing.JLabel();
        faturamento = new javax.swing.JLabel();
        iconCidades = new javax.swing.JLabel();
        cidades = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nomeDoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 50));

        tituloTela.setFont(new java.awt.Font("Segoe UI Black", 0, 64)); // NOI18N
        tituloTela.setForeground(new java.awt.Color(255, 255, 255));
        tituloTela.setText("MENU");
        getContentPane().add(tituloTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        painel.setBackground(new java.awt.Color(51, 0, 204));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloEmpresa.setFont(new java.awt.Font("Liberation Sans", 1, 64)); // NOI18N
        tituloEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        tituloEmpresa.setText("CROSSBUS");
        painel.add(tituloEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        btSair.setText("Sair");
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        painel.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 780, 150, 50));

        painelInteracao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.magenta, java.awt.Color.magenta, java.awt.Color.magenta, java.awt.Color.magenta));
        painelInteracao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bus-stop.png"))); // NOI18N
        iconVeiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iconVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconVeiculosMouseClicked(evt);
            }
        });
        painelInteracao.add(iconVeiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 120, 110));

        veiculos.setText("VEICULOS");
        painelInteracao.add(veiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        iconViagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ponteiro-de-parada-de-onibus(1).png"))); // NOI18N
        iconViagens.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelInteracao.add(iconViagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        viagens.setText("VIAGENS");
        painelInteracao.add(viagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        iconPassagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/forma-de-pagamento(1).png"))); // NOI18N
        iconPassagens.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelInteracao.add(iconPassagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 120, 100));

        passagensVendidas.setText("PASSAGENS VENDIDAS");
        painelInteracao.add(passagensVendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 140, 20));

        iconFaturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grafico-de-crescimento.png"))); // NOI18N
        iconFaturamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        painelInteracao.add(iconFaturamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        faturamento.setText("FATURAMENTO");
        painelInteracao.add(faturamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        iconCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cityscape.png"))); // NOI18N
        iconCidades.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iconCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconCidadesMouseClicked(evt);
            }
        });
        painelInteracao.add(iconCidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 140, 130));

        cidades.setText("CIDADES");
        painelInteracao.add(cidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        painel.add(painelInteracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 780, 470));

        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Confirmação de Logout", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();

            telaLogin login = new telaLogin();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void iconVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconVeiculosMouseClicked
        telaOnibus telaOnibus = new telaOnibus();
        telaOnibus.setVisible(true);
    }//GEN-LAST:event_iconVeiculosMouseClicked

    private void iconCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconCidadesMouseClicked
        TelaCidade telaCidade = new TelaCidade();
        telaCidade.setVisible(true);
    }//GEN-LAST:event_iconCidadesMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel cidades;
    private javax.swing.JLabel faturamento;
    private javax.swing.JLabel iconCidades;
    private javax.swing.JLabel iconFaturamento;
    private javax.swing.JLabel iconPassagens;
    private javax.swing.JLabel iconVeiculos;
    private javax.swing.JLabel iconViagens;
    private javax.swing.JLabel nomeDoUsuario;
    private javax.swing.JPanel painel;
    private javax.swing.JPanel painelInteracao;
    private javax.swing.JLabel passagensVendidas;
    private javax.swing.JLabel tituloEmpresa;
    private javax.swing.JLabel tituloTela;
    private javax.swing.JLabel veiculos;
    private javax.swing.JLabel viagens;
    // End of variables declaration//GEN-END:variables
}
