/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package passagensrodoviarias;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gabrielpaiva
 */
public class telaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastro
     */
    public telaCadastro() {
        initComponents();
        setSize(1280, 860);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        telaCadastro.RoundedPanel roundedPanel = new telaCadastro.RoundedPanel(40);
        roundedPanel.setLayout(new BorderLayout());
        roundedPanel.setBackground(new Color(99,33,99,70)); // Define a cor de fundo com transparência
        this.setTitle("Teste");
        
        
// Adicione outros componentes ao roundedPanel conforme necessário
// Exemplo: roundedPanel.add(new JLabel("Conteúdo do painel"));
        formPanel.setLayout(new BorderLayout());
        formPanel.add(roundedPanel, BorderLayout.CENTER);
    }
public class RoundedPanel extends JPanel {
    private int radius;

    public RoundedPanel(int radius) {
        this.radius = radius;
        setOpaque(false); // Torna o JPanel transparente
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Dimension arcs = new Dimension(radius, radius); // Tamanho do arco de borda

        int width = getWidth();
        int height = getHeight();
        Graphics2D graphics = (Graphics2D) g;
        graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Desenha o painel com bordas arredondadas
        graphics.setColor(getBackground());
        graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height);
        graphics.setColor(getForeground());
        graphics.drawRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formPanel = new javax.swing.JPanel();
        labelLogin = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        labelConfirmSenha = new javax.swing.JLabel();
        cadastrar = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        senha2 = new javax.swing.JPasswordField();
        nome = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        iconAnterior = new javax.swing.JLabel();
        iconBus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formPanel.setBackground(new java.awt.Color(0, 0, 255));
        formPanel.setForeground(new java.awt.Color(255, 255, 255));
        formPanel.setDoubleBuffered(false);
        formPanel.setOpaque(false);
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("Login");
        formPanel.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        labelSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelSenha.setText("Senha");
        formPanel.add(labelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        formPanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, -1));

        labelConfirmSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelConfirmSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelConfirmSenha.setText("Confirmar Senha");
        formPanel.add(labelConfirmSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        cadastrar.setBackground(new java.awt.Color(102, 102, 255));
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setText("Cadastrar");
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        formPanel.add(cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 130, 40));
        formPanel.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 220, -1));

        senha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senha2ActionPerformed(evt);
            }
        });
        formPanel.add(senha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 220, -1));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        formPanel.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        formPanel.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 220, -1));

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(255, 255, 255));
        labelEmail.setText("Email");
        formPanel.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(255, 255, 255));
        labelNome.setText("Nome completo");
        formPanel.add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        iconAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        iconAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAnteriorMouseClicked(evt);
            }
        });
        formPanel.add(iconAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 60));

        iconBus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bus.png"))); // NOI18N
        formPanel.add(iconBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CADASTRAR");
        formPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        getContentPane().add(formPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 540, 530));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CROSSBUS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background-cadastro-home.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, 1050));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
       // Obtém os valores dos campos
        String loginText = login.getText();
        char[] senhaArray = senha.getPassword();
        char[] senha2Array = senha2.getPassword();
        String nomeText = nome.getText();
        String emailText = email.getText();
        String senha = new String(senhaArray);
        String senha2 = new String(senha2Array);

        // Verificar se as senhas coincidem
        if (senha.equals(senha2)) {
            // Tentar inserir os dados no banco de dados
            boolean cadastradoComSucesso = BancoDeDados.inserirDadosNoBanco(loginText, senha, nomeText, emailText);

            if (cadastradoComSucesso) {
                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
                telaLogin login = new telaLogin();
                login.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar. Por favor, tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "As senhas não coincidem. Por favor, verifique e tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void senha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senha2ActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void iconAnteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAnteriorMouseClicked
        // TODO add your handling code here:
        telaLogin telaLogin = new telaLogin();
                telaLogin.setVisible(true);
                setVisible(false);
                dispose();
    }//GEN-LAST:event_iconAnteriorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField email;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel iconAnterior;
    private javax.swing.JLabel iconBus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelConfirmSenha;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senha;
    private javax.swing.JPasswordField senha2;
    // End of variables declaration//GEN-END:variables
}
